version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    command: npm run start
